#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.sendgrid.SendGridAutoConfiguration
#spring.application.name=pet-care
spring.jpa.properties.hibernate.default_batch_fetch_size=30

# ===============================
# EMAIL CONFIGURATION (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Thay b?ng ??a ch? Gmail c?a b?n
spring.mail.username=phamvantunghn2b@gmail.com

# Thay b?ng M?t kh?u ?ng d?ng 16 ký t? (App Password) - KHÔNG PH?I m?t kh?u ??ng nh?p
spring.mail.password=zoftdsogsjbjoxlc

# Các c?u hình b?t bu?c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000