spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/pet_care
    username: root
    password: 1234
    hikari: # Connection poll
      max-lifetime: 300000      # 5 phút
      idle-timeout: 60000       # 1 phút
      validation-timeout: 5000  # 5 giây
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: none
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: phamvu65cs@gmail.com
    templateId: d-d5d0b72e441f4da8913baf9e330aceeb
    verificationLink: http://localhost:8080/user/confirm-email

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  expiryMinutes: 1
  expiryDay: 14
  accessKey: f755f118db5972c1e60ba4c60b671278b1702610fb60d6cb926e809f56be96ce
  refreshKey: 6a47ad4b888173a219982ce0cfb91098a360611d4055da9988b8a1451804c261